CREATE SCHEMA VENDA_ONLINE;
DROP SCHEMA VENDA_ONLINE;
USE VENDA_ONLINE;
CREATE TABLE CLIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    CELULAR VARCHAR(20),
    DATA_NASCIMENTO DATE
);
CREATE TABLE PRODUTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    PRECO DECIMAL(10, 2),
    DESCRICAO TEXT,
    QUANTIDADE_ESTOQUE INT
);
CREATE TABLE PEDIDOS (
    NUMERO_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_COMPRA DATE,
    VALOR_TOTAL DECIMAL(10, 2),
    DATA_ENTREGA_ESTIMADA DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);
CREATE TABLE ITENS_PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    VALOR_UNITARIO DECIMAL(10, 2),
    VALOR_TOTAL DECIMAL(10, 2),
    FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDOS(NUMERO_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);